# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

future: true
# Site settings
title:              sumarsono.id
author:             Sumarsono
email:              sumarsono.wongbandar@gmail.com
description:        'Ikatlah ilmu dengan tulisan'
# the subpath of your site, e.g. /blog
baseurl:            ''
permalink:          pretty
# the base hostname & protocol for your site
url:                https://sumarsono.id
github_username:    sumarouno
telegram_username:  unomind
disqus_username:    sumarouno

# Build settings
markdown:           kramdown
highlighter:        rouge

compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   all

sitemap:
  lastmod:
  priority: 0.5
  changefreq: monthly
  exclude: 'no'

gems:
  - jemoji
