# Site settings
title: "sumarsono.net"
email: sumarsono.wongbandar@gmail.com
description: "Sebuah Kisah"
baseurl: ""
url: "https://sumarsono.net/"
title_description: "Sebuah Kisah"
title_image: "https://secure.gravatar.com/avatar/09b66313d58720e08cf4c633528cdef8"
#google_analytics: "UA-20365477-4"
#disqus_account: cartenoire
github_repository: https://github.com/sumarouno
#addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: sumarsono_id
github_username:  sumarouno
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
facebook_link: http://facebook.com/unomind

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
